name: Python CI

on:
  push:
    branches:
      - main
      - phase-1
      - phase-2
      - phase-3

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Pip güncelle
        run: python -m pip install --upgrade pip

      - name: Python syntax kontrolü
        run: python -m py_compile src/*.py